<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ========== HAIR CARE PRODUCTS ==========
            [
                'name' => 'Professional Shampoo',
                'category' => 'hair_care',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 350.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Professional Conditioner',
                'category' => 'hair_care',
                'current_stock' => 12,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 380.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Hair Treatment Mask',
                'category' => 'hair_care',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'jars',
                'cost' => 550.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Leave-in Conditioner',
                'category' => 'hair_care',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'bottles',
                'cost' => 420.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Heat Protectant Spray',
                'category' => 'hair_care',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'bottles',
                'cost' => 380.00,
                'supplier' => 'Beauty Supply Co.',
            ],

            // ========== HAIR COLOR PRODUCTS ==========
            [
                'name' => 'Hair Color - Black',
                'category' => 'hair_color',
                'current_stock' => 20,
                'minimum_stock' => 8,
                'unit' => 'tubes',
                'cost' => 280.00,
                'supplier' => 'Davines Philippines',
            ],
            [
                'name' => 'Hair Color - Brown Shades',
                'category' => 'hair_color',
                'current_stock' => 25,
                'minimum_stock' => 10,
                'unit' => 'tubes',
                'cost' => 280.00,
                'supplier' => 'Davines Philippines',
            ],
            [
                'name' => 'Hair Color - Blonde Shades',
                'category' => 'hair_color',
                'current_stock' => 15,
                'minimum_stock' => 6,
                'unit' => 'tubes',
                'cost' => 320.00,
                'supplier' => 'Schwarzkopf PH',
            ],
            [
                'name' => 'Hair Color - Fashion Colors',
                'category' => 'hair_color',
                'current_stock' => 18,
                'minimum_stock' => 8,
                'unit' => 'tubes',
                'cost' => 350.00,
                'supplier' => 'Schwarzkopf PH',
            ],
            [
                'name' => 'Hair Bleach Powder',
                'category' => 'hair_color',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'packs',
                'cost' => 450.00,
                'supplier' => 'Schwarzkopf PH',
            ],
            [
                'name' => 'Developer 6%',
                'category' => 'hair_color',
                'current_stock' => 12,
                'minimum_stock' => 5,
                'unit' => 'liters',
                'cost' => 280.00,
                'supplier' => 'Davines Philippines',
            ],
            [
                'name' => 'Developer 9%',
                'category' => 'hair_color',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'liters',
                'cost' => 280.00,
                'supplier' => 'Davines Philippines',
            ],
            [
                'name' => 'Developer 12%',
                'category' => 'hair_color',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'liters',
                'cost' => 280.00,
                'supplier' => 'Davines Philippines',
            ],

            // ========== HAIR TREATMENT ==========
            [
                'name' => 'Keratin Treatment',
                'category' => 'hair_treatment',
                'current_stock' => 6,
                'minimum_stock' => 2,
                'unit' => 'bottles',
                'cost' => 1500.00,
                'supplier' => 'Keratin Express',
            ],
            [
                'name' => 'Rebonding Cream Set',
                'category' => 'hair_treatment',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'sets',
                'cost' => 850.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Neutralizer',
                'category' => 'hair_treatment',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'bottles',
                'cost' => 320.00,
                'supplier' => 'Beauty Supply Co.',
            ],

            // ========== STYLING PRODUCTS ==========
            [
                'name' => 'Hair Spray',
                'category' => 'styling',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'cans',
                'cost' => 280.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Hair Mousse',
                'category' => 'styling',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'bottles',
                'cost' => 320.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Hair Gel',
                'category' => 'styling',
                'current_stock' => 6,
                'minimum_stock' => 3,
                'unit' => 'jars',
                'cost' => 180.00,
                'supplier' => 'Beauty Supply Co.',
            ],
            [
                'name' => 'Hair Serum',
                'category' => 'styling',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'bottles',
                'cost' => 450.00,
                'supplier' => 'Beauty Supply Co.',
            ],

            // ========== NAIL POLISH ==========
            [
                'name' => 'Regular Nail Polish - Assorted Colors',
                'category' => 'nail_polish',
                'current_stock' => 50,
                'minimum_stock' => 20,
                'unit' => 'bottles',
                'cost' => 85.00,
                'supplier' => 'OPI Philippines',
            ],
            [
                'name' => 'Gel Polish - Assorted Colors',
                'category' => 'nail_polish',
                'current_stock' => 40,
                'minimum_stock' => 15,
                'unit' => 'bottles',
                'cost' => 180.00,
                'supplier' => 'OPI Philippines',
            ],
            [
                'name' => 'Base Coat',
                'category' => 'nail_polish',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 150.00,
                'supplier' => 'OPI Philippines',
            ],
            [
                'name' => 'Top Coat',
                'category' => 'nail_polish',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 150.00,
                'supplier' => 'OPI Philippines',
            ],
            [
                'name' => 'French White Polish',
                'category' => 'nail_polish',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'bottles',
                'cost' => 120.00,
                'supplier' => 'OPI Philippines',
            ],

            // ========== NAIL CARE ==========
            [
                'name' => 'Cuticle Oil',
                'category' => 'nail_care',
                'current_stock' => 12,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 180.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Cuticle Remover',
                'category' => 'nail_care',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'bottles',
                'cost' => 150.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Nail Cleanser/Dehydrator',
                'category' => 'nail_care',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'bottles',
                'cost' => 200.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Acetone (Nail Polish Remover)',
                'category' => 'nail_care',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'liters',
                'cost' => 120.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Nail Files - 100/180 grit',
                'category' => 'nail_care',
                'current_stock' => 50,
                'minimum_stock' => 20,
                'unit' => 'pcs',
                'cost' => 15.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Buffer Blocks',
                'category' => 'nail_care',
                'current_stock' => 30,
                'minimum_stock' => 10,
                'unit' => 'pcs',
                'cost' => 25.00,
                'supplier' => 'Nail Supply PH',
            ],

            // ========== NAIL EXTENSIONS ==========
            [
                'name' => 'Soft Gel Tips',
                'category' => 'nail_extensions',
                'current_stock' => 20,
                'minimum_stock' => 8,
                'unit' => 'boxes',
                'cost' => 350.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Acrylic Powder - Clear',
                'category' => 'nail_extensions',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'jars',
                'cost' => 450.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Acrylic Powder - Pink',
                'category' => 'nail_extensions',
                'current_stock' => 6,
                'minimum_stock' => 2,
                'unit' => 'jars',
                'cost' => 450.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Acrylic Liquid Monomer',
                'category' => 'nail_extensions',
                'current_stock' => 6,
                'minimum_stock' => 2,
                'unit' => 'bottles',
                'cost' => 550.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Nail Glue',
                'category' => 'nail_extensions',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 80.00,
                'supplier' => 'Nail Supply PH',
            ],
            [
                'name' => 'Nail Forms',
                'category' => 'nail_extensions',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'rolls',
                'cost' => 150.00,
                'supplier' => 'Nail Supply PH',
            ],

            // ========== NAIL ART ==========
            [
                'name' => 'Nail Charms - Assorted',
                'category' => 'nail_art',
                'current_stock' => 25,
                'minimum_stock' => 10,
                'unit' => 'packs',
                'cost' => 120.00,
                'supplier' => 'Nail Art Supplies',
            ],
            [
                'name' => 'Rhinestones - Assorted',
                'category' => 'nail_art',
                'current_stock' => 20,
                'minimum_stock' => 8,
                'unit' => 'packs',
                'cost' => 150.00,
                'supplier' => 'Nail Art Supplies',
            ],
            [
                'name' => 'Nail Art Brushes Set',
                'category' => 'nail_art',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'sets',
                'cost' => 280.00,
                'supplier' => 'Nail Art Supplies',
            ],
            [
                'name' => 'Nail Stickers - Assorted',
                'category' => 'nail_art',
                'current_stock' => 30,
                'minimum_stock' => 10,
                'unit' => 'sheets',
                'cost' => 50.00,
                'supplier' => 'Nail Art Supplies',
            ],

            // ========== SPA PRODUCTS ==========
            [
                'name' => 'Foot Soak Salt',
                'category' => 'spa',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'packs',
                'cost' => 180.00,
                'supplier' => 'Spa Essentials PH',
            ],
            [
                'name' => 'Foot Scrub',
                'category' => 'spa',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'jars',
                'cost' => 350.00,
                'supplier' => 'Spa Essentials PH',
            ],
            [
                'name' => 'Hand Scrub',
                'category' => 'spa',
                'current_stock' => 8,
                'minimum_stock' => 3,
                'unit' => 'jars',
                'cost' => 320.00,
                'supplier' => 'Spa Essentials PH',
            ],
            [
                'name' => 'Massage Oil',
                'category' => 'spa',
                'current_stock' => 12,
                'minimum_stock' => 5,
                'unit' => 'bottles',
                'cost' => 280.00,
                'supplier' => 'Spa Essentials PH',
            ],
            [
                'name' => 'Moisturizing Lotion',
                'category' => 'spa',
                'current_stock' => 15,
                'minimum_stock' => 6,
                'unit' => 'bottles',
                'cost' => 250.00,
                'supplier' => 'Spa Essentials PH',
            ],
            [
                'name' => 'Paraffin Wax',
                'category' => 'spa',
                'current_stock' => 6,
                'minimum_stock' => 2,
                'unit' => 'blocks',
                'cost' => 400.00,
                'supplier' => 'Spa Essentials PH',
            ],
            [
                'name' => 'Foot Mask',
                'category' => 'spa',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'packs',
                'cost' => 150.00,
                'supplier' => 'Spa Essentials PH',
            ],

            // ========== CONSUMABLES/SUPPLIES ==========
            [
                'name' => 'Cotton Balls',
                'category' => 'consumables',
                'current_stock' => 20,
                'minimum_stock' => 8,
                'unit' => 'packs',
                'cost' => 45.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Cotton Pads',
                'category' => 'consumables',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'packs',
                'cost' => 65.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Aluminum Foil',
                'category' => 'consumables',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'rolls',
                'cost' => 180.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Disposable Gloves',
                'category' => 'consumables',
                'current_stock' => 25,
                'minimum_stock' => 10,
                'unit' => 'boxes',
                'cost' => 280.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Disposable Capes',
                'category' => 'consumables',
                'current_stock' => 15,
                'minimum_stock' => 5,
                'unit' => 'packs',
                'cost' => 150.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Neck Strips',
                'category' => 'consumables',
                'current_stock' => 10,
                'minimum_stock' => 4,
                'unit' => 'rolls',
                'cost' => 120.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Salon Towels',
                'category' => 'consumables',
                'current_stock' => 30,
                'minimum_stock' => 15,
                'unit' => 'pcs',
                'cost' => 85.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Sanitizer/Disinfectant',
                'category' => 'consumables',
                'current_stock' => 12,
                'minimum_stock' => 5,
                'unit' => 'liters',
                'cost' => 180.00,
                'supplier' => 'General Supplies',
            ],
            [
                'name' => 'Barbicide Solution',
                'category' => 'consumables',
                'current_stock' => 6,
                'minimum_stock' => 2,
                'unit' => 'bottles',
                'cost' => 450.00,
                'supplier' => 'Beauty Supply Co.',
            ],
        ];

        foreach ($items as $item) {
            InventoryItem::updateOrCreate(
                ['name' => $item['name']],
                $item
            );
        }
    }
}
